### ISSUE TITLE
Launching apps

### ISSUE THREAD

**Issue by rosensvv** [udevbe/greenfield#100]
I am trying to launch apps by simply installing them and launching them from the alacritty terminal. They all fail (tried to launch another alacritty, pcmanfm etc) with messages like cannot open display, connection refused or no compositor listening. What should be the workflow for installing and launching apps? What about Xwayland? Also can I have one of the buttons start an Xwayland session (I can see the xterm container is configured as such on the docker-compose, can I have them launch seperately rather than both launching at the same time?). Ideally I would want to install a wayland app launcher like rofi and have it launch other apps.

**Comment by Zubnix** [comment]
Are you launching from a container? In a non-container the only thing that is required to make XWayland work is to set the environment variable `DISPLAY=:1`. If you are running in a container you need to use the additional mount points & environment variables like they are configured in the xterm docker-compose container. This is required so that your X11 application can talk to XWayland (which is essentially just an X11 display server).

If you want to launch applications on demand you need a way of telling your server to start the container or application. This can be done with an HTTP REST-call from your browser & custom HTTP server implementation, or by using an existing (Wayland) application like a terminal or dedicated launcher. The drawback of the latter is that this won't work in a container unless you bundle all your apps in the same container as they need to be available on the PATH that your launcher uses.

**Comment by rosensvv** [comment]
My current setup is trying to launch anything from the alactritty container (after they have been installed of course) - it doesn't work, not even launching another alacritty terminal from the existing one (errors like:  cannot open display, connection refused or no compositor listening). My other question is whether I can have the connect buttons on the demo-compositor launch specific containers (say one button launches the alacritty container and the other one launches the Xwayland environment container)

**Comment by Zubnix** [comment]
I'm not sure what the issue is. I can not reproduce it locally using docker compose. All ui applications installed in the Alacritty container work without issues if I include the additional X volume & environment variables. Tested apps including xterm, kwrite, firefox, alacritty itself etc.

Judging by the errors you describe, sounds like either environment variables are not set and/or volumes are not mounted that contain the unix socket which the apps use to connect to the compositor-proxy.

My alacritty docker compose section looks like this:
```
  alacritty:
    pid: 'service:compositor-proxy'
    build:
      context: example-apps/alacritty
      dockerfile: Dockerfile
    privileged: false
    volumes:
      - xdg-runtime-dir:/xdg-runtime-dir
      - x11-unix:/tmp/.X11-unix
    environment:
      WAYLAND_DISPLAY: wayland-0
      XAUTHORITY: /tmp/.X11-unix/Xauthority
      XDG_RUNTIME_DIR: /xdg-runtime-dir
      DISPLAY: ':1'
    restart: always
```
